### ISSUE TITLE
List "icon" not visible

### ISSUE THREAD

**Issue by 7k50** [willjohnson/dashing-asana-tasks#1]
Hello! I just tried this widget, and was successfully able to authenticate myself using my Asana Personal Access Token.

My list got populated with my tasks "Marked For Today".

However, the "complete/not complete" Icons are not visible on the left side of each task item.
This is what I'm referring to. Screenshot from your README.md. These are missing:

<img width="28" alt="screen shot 2017-07-15 at 20 57 39" src="https://user-images.githubusercontent.com/14942350/28242003-b3fb2902-69a0-11e7-8499-5cba3ad36818.png">

**Comment by willjohnson** [comment]
You might have a newer version of font-awesome inside dashing than the one this was written to support. Look in the assets/stylesheets folder to see. If you are on a newer version you might try changing the icon name in the jobs file from "icon-check-empty" to "far fa-square".
